---
# this config.yaml is passed to Snakefile in pipeline-structural-variation subfolder.
# Snakemake is run from this pipeline-structural-variation folder; it is necessary to
# pass an appropriate path to the input-files (the ../ prefix is sufficient for this demo)

# FASTQ file or folder containing FASTQ files
input_fastq: "../RawData/GM24385_nf7_chr8.fastq.gz"
# FASTA file containing the reference genome
reference_fasta: "../ReferenceData/human_g1k_v37_chr8.fasta"
# Minimum SV length
min_sv_length: 40
# Maximum SV length
max_sv_length: 1000000
# Min read length. Shorter reads will be discarded
min_read_length: 1000
# Min mapping quality. Reads will lower mapping quality will be discarded
min_read_mapping_quality: 20
# Minimum read support required to call a SV (auto for auto-detect)
min_read_support: 'auto'
# Sample name
sample_name: "GM24385.nf7.chr8_c"

#################################
## General pipeline parameters ##
#################################
# path to directory holding the working directory:
workdir_top: "../Analysis"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-structural-variation.git"

##################################
## Tutorial specific parameters ##
##################################
tutorialText: True
biocGenome: "hg19"
GeneIdMappings: "org.Hs.eg.db"
GenomeAnnotation: "TxDb.Hsapiens.UCSC.hg19.knownGene"
