channels:
    - bioconda
    - conda-forge
    - r
dependencies:
    - snakemake-minimal
    - minimap2
    - sniffles
    - samtools
    - nanofilt
    - nanoplot
    - pybedtools
    - bedtools
    - bcftools
    - pysam
    - scipy
    - tqdm
    - vcftools
    - vcflib
    - make
    - mosdepth
    - pyfaidx
    - pyvcf
    - progressbar2
    - python-Levenshtein
    - intervaltree==2.1.0
    - rtg-tools
    - r
    - r-nanopore
    - imagemagick
    - graphviz
    - pandoc
    - igv
